"""
Base Strategy Class - Abstract base for all trading strategies
"""
from abc import ABC, abstractmethod
from dataclasses import dataclass, field
from datetime import datetime
from enum import Enum
from typing import Optional, List, Dict, Any

import pandas as pd


class StrategyType(Enum):
    """Types of options strategies."""
    LONG_CALL = "long_call"
    LONG_PUT = "long_put"
    SHORT_CALL = "short_call"
    SHORT_PUT = "short_put"
    BULL_CALL_SPREAD = "bull_call_spread"
    BEAR_PUT_SPREAD = "bear_put_spread"
    BEAR_CALL_SPREAD = "bear_call_spread"  # Credit spread - SELL call, BUY call hedge
    BULL_PUT_SPREAD = "bull_put_spread"    # Credit spread - SELL put, BUY put hedge
    IRON_CONDOR = "iron_condor"
    STRADDLE = "straddle"
    STRANGLE = "strangle"
    BUTTERFLY = "butterfly"
    CALENDAR_SPREAD = "calendar_spread"


class TradeDirection(Enum):
    """Trade direction."""
    BUY = "BUY"
    SELL = "SELL"


@dataclass
class OptionLeg:
    """Represents a single leg of an options strategy."""
    symbol: str
    strike: float
    option_type: str  # CE or PE
    expiry: datetime
    direction: TradeDirection
    quantity: int
    entry_price: Optional[float] = None
    current_price: Optional[float] = None
    instrument_token: Optional[int] = None
    
    @property
    def is_call(self) -> bool:
        return self.option_type == "CE"
    
    @property
    def is_put(self) -> bool:
        return self.option_type == "PE"
    
    @property
    def is_long(self) -> bool:
        return self.direction == TradeDirection.BUY
    
    @property
    def is_short(self) -> bool:
        return self.direction == TradeDirection.SELL
    
    def pnl(self) -> float:
        """Calculate P&L for this leg."""
        if not self.entry_price or not self.current_price:
            return 0
        
        diff = self.current_price - self.entry_price
        if self.is_short:
            diff = -diff
        
        return diff * self.quantity


@dataclass
class StrategySignal:
    """Signal generated by a strategy."""
    strategy_type: StrategyType
    underlying: str
    legs: List[OptionLeg]
    entry_time: datetime
    confidence: float  # 0 to 1
    expected_profit: float
    max_loss: float
    stop_loss: float
    target: float
    rationale: str
    metrics: Dict[str, Any] = field(default_factory=dict)
    
    @property
    def risk_reward_ratio(self) -> float:
        """
        Calculate risk/reward ratio as target profit / stop loss amount.
        
        For option buying: reward is target profit, risk is stop loss amount
        For option selling: reward is premium received, risk is potential loss
        """
        # Use stop_loss as the risk (not max_loss)
        # stop_loss is the amount we lose if SL is hit
        if self.stop_loss == 0:
            # Fallback to max_loss if no SL defined
            if self.max_loss == 0:
                return 0
            return abs(self.expected_profit / self.max_loss)
        
        # RR = potential reward / potential risk
        return abs(self.expected_profit / self.stop_loss) if self.stop_loss > 0 else 0
    
    def to_dict(self) -> Dict[str, Any]:
        return {
            "strategy_type": self.strategy_type.value,
            "underlying": self.underlying,
            "legs": [
                {
                    "symbol": leg.symbol,
                    "strike": leg.strike,
                    "option_type": leg.option_type,
                    "expiry": leg.expiry.isoformat(),
                    "direction": leg.direction.value,
                    "quantity": leg.quantity,
                    "entry_price": leg.entry_price,
                }
                for leg in self.legs
            ],
            "entry_time": self.entry_time.isoformat(),
            "confidence": self.confidence,
            "expected_profit": self.expected_profit,
            "max_loss": self.max_loss,
            "stop_loss": self.stop_loss,
            "target": self.target,
            "risk_reward_ratio": self.risk_reward_ratio,
            "rationale": self.rationale,
            "metrics": self.metrics,
        }


from config.settings import LIQUIDITY_GUARD


# Indices vs stocks - used for reward scaling
INDEX_UNDERLYINGS = ["NIFTY", "BANKNIFTY", "FINNIFTY", "SENSEX"]


class BaseStrategy(ABC):
    """
    Abstract base class for all trading strategies.
    """
    
    def __init__(self, underlying: str):
        self.underlying = underlying
        self.name: str = "Base Strategy"
        self.description: str = ""
        self.strategy_type: StrategyType = None
        self.min_confidence: float = 0.6
        self.ml_override: bool = False  # When True, skip OI sentiment & confidence gates
    
    @property
    def is_index(self) -> bool:
        """Whether this underlying is an index (vs a stock)."""
        return self.underlying in INDEX_UNDERLYINGS
        
    @abstractmethod
    def analyze(self, options_chain: pd.DataFrame, metrics: Dict[str, Any]) -> Optional[StrategySignal]:
        """
        Analyze market data and generate trading signal if conditions are met.
        
        Args:
            options_chain: Options chain DataFrame
            metrics: Dictionary containing OI, volatility, and other metrics
            
        Returns:
            StrategySignal if conditions are met, None otherwise
        """
        pass
    
    @abstractmethod
    def calculate_stop_loss(self, entry_price: float, **kwargs) -> float:
        """
        Calculate stop loss price.
        
        Args:
            entry_price: Entry price
            **kwargs: Additional parameters
            
        Returns:
            Stop loss price
        """
        pass
    
    @abstractmethod
    def calculate_target(self, entry_price: float, **kwargs) -> float:
        """
        Calculate target price.
        
        Args:
            entry_price: Entry price
            **kwargs: Additional parameters
            
        Returns:
            Target price
        """
        pass
    
    def should_exit(self, signal: StrategySignal, current_prices: Dict[str, float]) -> tuple[bool, str]:
        """
        Check if position should be exited.
        
        Args:
            signal: The original signal
            current_prices: Current prices for each leg
            
        Returns:
            Tuple of (should_exit, reason)
        """
        total_pnl = 0
        
        for leg in signal.legs:
            current_price = current_prices.get(leg.symbol, leg.entry_price)
            leg.current_price = current_price
            total_pnl += leg.pnl()
        
        # Check stop loss
        if total_pnl <= -signal.stop_loss:
            return True, "Stop loss hit"
        
        # Check target
        if total_pnl >= signal.target:
            return True, "Target achieved"
        
        return False, ""
    
    def validate_conditions(self, metrics: Dict[str, Any]) -> tuple[bool, str]:
        """
        Validate if basic conditions are met for strategy execution.
        
        Args:
            metrics: Market metrics dictionary
            
        Returns:
            Tuple of (is_valid, reason)
        """
        if not metrics:
            return False, "No metrics available"
        
        return True, ""
    
    def check_leg_liquidity(self, option_row: pd.Series) -> tuple[bool, str]:
        """
        Check if a single option leg meets minimum liquidity thresholds.
        
        Examines volume, open interest, and bid-ask spread width.
        Thresholds differ for indices (more liquid) vs stocks.
        
        Args:
            option_row: A single row from the options chain DataFrame,
                        expected to have columns: volume, oi, bid, ask, ltp, symbol.
            
        Returns:
            (True, "") if liquid enough, (False, reason) otherwise.
        """
        if not LIQUIDITY_GUARD.get("enabled", True):
            return True, ""
        
        symbol = option_row.get("symbol", "?")
        idx = self.is_index
        
        # ── Volume check ─────────────────────────────────────────────
        min_vol = LIQUIDITY_GUARD.get(
            "min_volume_index" if idx else "min_volume_stock", 500
        )
        volume = option_row.get("volume", 0) or 0
        if volume < min_vol:
            return False, (
                f"Volume too low on {symbol}: {volume} < {min_vol}"
            )
        
        # ── Open Interest check ──────────────────────────────────────
        min_oi = LIQUIDITY_GUARD.get(
            "min_oi_index" if idx else "min_oi_stock", 1000
        )
        oi = option_row.get("oi", 0) or 0
        if oi < min_oi:
            return False, (
                f"OI too low on {symbol}: {oi} < {min_oi}"
            )
        
        # ── Bid-Ask spread check ─────────────────────────────────────
        max_spread_pct = LIQUIDITY_GUARD.get("max_bid_ask_spread_pct", 5.0)
        bid = option_row.get("bid", 0) or 0
        ask = option_row.get("ask", 0) or 0
        
        if bid > 0 and ask > 0:
            mid = (bid + ask) / 2
            spread_pct = ((ask - bid) / mid) * 100 if mid > 0 else 0
            if spread_pct > max_spread_pct:
                return False, (
                    f"Bid-ask spread too wide on {symbol}: "
                    f"{spread_pct:.1f}% > {max_spread_pct}%"
                )
        
        return True, ""
    
    def __repr__(self) -> str:
        return f"{self.__class__.__name__}(underlying={self.underlying})"
