"""
Base Strategy Class - Abstract base for all trading strategies
"""
from abc import ABC, abstractmethod
from dataclasses import dataclass, field
from datetime import datetime
from enum import Enum
from typing import Optional, List, Dict, Any

import pandas as pd


class StrategyType(Enum):
    """Types of options strategies."""
    LONG_CALL = "long_call"
    LONG_PUT = "long_put"
    SHORT_CALL = "short_call"
    SHORT_PUT = "short_put"
    BULL_CALL_SPREAD = "bull_call_spread"
    BEAR_PUT_SPREAD = "bear_put_spread"
    IRON_CONDOR = "iron_condor"
    STRADDLE = "straddle"
    STRANGLE = "strangle"
    BUTTERFLY = "butterfly"
    CALENDAR_SPREAD = "calendar_spread"


class TradeDirection(Enum):
    """Trade direction."""
    BUY = "BUY"
    SELL = "SELL"


@dataclass
class OptionLeg:
    """Represents a single leg of an options strategy."""
    symbol: str
    strike: float
    option_type: str  # CE or PE
    expiry: datetime
    direction: TradeDirection
    quantity: int
    entry_price: Optional[float] = None
    current_price: Optional[float] = None
    instrument_token: Optional[int] = None
    
    @property
    def is_call(self) -> bool:
        return self.option_type == "CE"
    
    @property
    def is_put(self) -> bool:
        return self.option_type == "PE"
    
    @property
    def is_long(self) -> bool:
        return self.direction == TradeDirection.BUY
    
    @property
    def is_short(self) -> bool:
        return self.direction == TradeDirection.SELL
    
    def pnl(self) -> float:
        """Calculate P&L for this leg."""
        if not self.entry_price or not self.current_price:
            return 0
        
        diff = self.current_price - self.entry_price
        if self.is_short:
            diff = -diff
        
        return diff * self.quantity


@dataclass
class StrategySignal:
    """Signal generated by a strategy."""
    strategy_type: StrategyType
    underlying: str
    legs: List[OptionLeg]
    entry_time: datetime
    confidence: float  # 0 to 1
    expected_profit: float
    max_loss: float
    stop_loss: float
    target: float
    rationale: str
    metrics: Dict[str, Any] = field(default_factory=dict)
    
    @property
    def risk_reward_ratio(self) -> float:
        if self.max_loss == 0:
            return 0
        return abs(self.expected_profit / self.max_loss)
    
    def to_dict(self) -> Dict[str, Any]:
        return {
            "strategy_type": self.strategy_type.value,
            "underlying": self.underlying,
            "legs": [
                {
                    "symbol": leg.symbol,
                    "strike": leg.strike,
                    "option_type": leg.option_type,
                    "expiry": leg.expiry.isoformat(),
                    "direction": leg.direction.value,
                    "quantity": leg.quantity,
                    "entry_price": leg.entry_price,
                }
                for leg in self.legs
            ],
            "entry_time": self.entry_time.isoformat(),
            "confidence": self.confidence,
            "expected_profit": self.expected_profit,
            "max_loss": self.max_loss,
            "stop_loss": self.stop_loss,
            "target": self.target,
            "risk_reward_ratio": self.risk_reward_ratio,
            "rationale": self.rationale,
            "metrics": self.metrics,
        }


class BaseStrategy(ABC):
    """
    Abstract base class for all trading strategies.
    """
    
    def __init__(self, underlying: str):
        self.underlying = underlying
        self.name: str = "Base Strategy"
        self.description: str = ""
        self.strategy_type: StrategyType = None
        self.min_confidence: float = 0.6
        
    @abstractmethod
    def analyze(self, options_chain: pd.DataFrame, metrics: Dict[str, Any]) -> Optional[StrategySignal]:
        """
        Analyze market data and generate trading signal if conditions are met.
        
        Args:
            options_chain: Options chain DataFrame
            metrics: Dictionary containing OI, volatility, and other metrics
            
        Returns:
            StrategySignal if conditions are met, None otherwise
        """
        pass
    
    @abstractmethod
    def calculate_stop_loss(self, entry_price: float, **kwargs) -> float:
        """
        Calculate stop loss price.
        
        Args:
            entry_price: Entry price
            **kwargs: Additional parameters
            
        Returns:
            Stop loss price
        """
        pass
    
    @abstractmethod
    def calculate_target(self, entry_price: float, **kwargs) -> float:
        """
        Calculate target price.
        
        Args:
            entry_price: Entry price
            **kwargs: Additional parameters
            
        Returns:
            Target price
        """
        pass
    
    def should_exit(self, signal: StrategySignal, current_prices: Dict[str, float]) -> tuple[bool, str]:
        """
        Check if position should be exited.
        
        Args:
            signal: The original signal
            current_prices: Current prices for each leg
            
        Returns:
            Tuple of (should_exit, reason)
        """
        total_pnl = 0
        
        for leg in signal.legs:
            current_price = current_prices.get(leg.symbol, leg.entry_price)
            leg.current_price = current_price
            total_pnl += leg.pnl()
        
        # Check stop loss
        if total_pnl <= -signal.stop_loss:
            return True, "Stop loss hit"
        
        # Check target
        if total_pnl >= signal.target:
            return True, "Target achieved"
        
        return False, ""
    
    def validate_conditions(self, metrics: Dict[str, Any]) -> tuple[bool, str]:
        """
        Validate if basic conditions are met for strategy execution.
        
        Args:
            metrics: Market metrics dictionary
            
        Returns:
            Tuple of (is_valid, reason)
        """
        if not metrics:
            return False, "No metrics available"
        
        return True, ""
    
    def __repr__(self) -> str:
        return f"{self.__class__.__name__}(underlying={self.underlying})"
